script_arg <- commandArgs(trailingOnly = FALSE)[grep("^--file=", commandArgs(trailingOnly = FALSE))]
script_path <- normalizePath(sub("^--file=", "", script_arg), winslash = "/")
docs_dir <- dirname(script_path)
app_dir <- dirname(docs_dir)
guide_dir <- file.path(docs_dir, "guide")
output_file <- file.path(docs_dir, "VARG-Tools_User_Guide.md")
combined_qmd_file <- file.path(guide_dir, "VARG-Tools_User_Guide.qmd")

chapter_files <- c(
  "index.qmd",
  "getting-started.qmd",
  "walkthrough.qmd",
  "processing.qmd",
  "visualization.qmd",
  "chronology.qmd",
  "troubleshooting.qmd",
  "reference.qmd"
)

chapter_paths <- file.path(guide_dir, chapter_files)
guide_asset_files <- c(
  "build_workflow_map.R",
  "workflow-map.png",
  "ilr-concept.png",
  "gmm-concept.png",
  "sc-concept.png",
  "phase-concept.png"
)
source_files <- c(script_path, chapter_paths, file.path(guide_dir, guide_asset_files))
source_digest <- paste(
  paste0(basename(source_files), "=", unname(tools::md5sum(source_files))),
  collapse = ";"
)
source_digest_marker <- paste0("<!-- Guide source digest: ", source_digest, " -->")

slugify <- function(text) {
  slug <- tolower(iconv(text, to = "ASCII//TRANSLIT"))
  slug <- gsub("[^a-z0-9]+", "-", slug)
  gsub("(^-|-$)", "", slug)
}

read_chapter <- function(filename) {
  path <- file.path(guide_dir, filename)
  lines <- readLines(path, warn = FALSE, encoding = "UTF-8")
  if (length(lines) < 3L || lines[[1]] != "---") {
    stop("Missing YAML front matter in ", path, call. = FALSE)
  }

  yaml_end <- which(lines[-1] == "---")
  if (length(yaml_end) == 0L) {
    stop("Unclosed YAML front matter in ", path, call. = FALSE)
  }
  yaml_end <- yaml_end[[1]] + 1L
  yaml <- lines[2:(yaml_end - 1L)]
  title_line <- grep("^title:[[:space:]]*", yaml, value = TRUE)
  if (length(title_line) != 1L) {
    stop("Expected one title in ", path, call. = FALSE)
  }
  title <- sub("^title:[[:space:]]*", "", title_line)
  title <- gsub('^"|"$', "", title)
  body <- if (yaml_end < length(lines)) lines[(yaml_end + 1L):length(lines)] else character(0)

  list(filename = filename, title = title, body = body)
}

chapters <- lapply(chapter_files, read_chapter)
title_slugs <- setNames(vapply(chapters, function(x) slugify(x$title), character(1)), chapter_files)

rewrite_chapter_links <- function(lines) {
  for (filename in chapter_files) {
    lines <- gsub(paste0("](", filename, "#"), "](#", lines, fixed = TRUE)
    lines <- gsub(
      paste0("](", filename, ")"),
      paste0("](#", title_slugs[[filename]], ")"),
      lines,
      fixed = TRUE
    )
  }

  lines
}

rewrite_app_images <- function(lines) {
  gsub(
    "\\]\\((?:\\./)?([^/:)]+\\.(?:png|jpe?g|svg|gif|webp))\\)",
    "](guide-assets/\\1)",
    lines,
    perl = TRUE,
    ignore.case = TRUE
  )
}

add_heading_anchors <- function(lines) {
  output <- character(0)
  used <- character(0)

  for (line in lines) {
    if (grepl("^#{1,6}[[:space:]]+", line)) {
      heading <- sub("^#{1,6}[[:space:]]+", "", line)
      heading <- gsub("[`*_]", "", heading)
      anchor <- slugify(heading)
      if (nzchar(anchor)) {
        base_anchor <- anchor
        counter <- 2L
        while (anchor %in% used) {
          anchor <- paste0(base_anchor, "-", counter)
          counter <- counter + 1L
        }
        used <- c(used, anchor)
        output <- c(output, paste0('<a id="', anchor, '"></a>'))
      }
    }
    output <- c(output, line)
  }

  output
}

global_lines <- readLines(file.path(app_dir, "global.R"), warn = FALSE, encoding = "UTF-8")
version_line <- grep('^APP_VERSION[[:space:]]*<-[[:space:]]*"', global_lines, value = TRUE)
if (length(version_line) != 1L) {
  stop("Could not determine APP_VERSION from global.R", call. = FALSE)
}
app_version <- sub('^[^"]*"([^"]+)".*$', "\\1", version_line)

output <- c(
  "<!-- Generated by docs/build_in_app_guide.R from docs/guide/*.qmd. Do not edit this file directly. -->",
  source_digest_marker,
  ""
)

for (i in seq_along(chapters)) {
  chapter <- chapters[[i]]
  body <- rewrite_app_images(rewrite_chapter_links(chapter$body))
  chapter_block <- c(
    paste0("# ", chapter$title),
    if (i == 1L) c(
      "",
      paste0(
        '<p class="guide-meta"><span><strong>Version:</strong> ', app_version,
        '</span><span><strong>Guide updated:</strong> ', Sys.Date(), "</span></p>"
      )
    ) else character(0),
    "",
    body
  )
  chapter_block <- add_heading_anchors(chapter_block)

  if (i > 1L) {
    output <- c(output, "", "---", "")
  }
  output <- c(output, chapter_block)
}

writeLines(output, output_file, useBytes = TRUE)

combined_qmd <- c(
  "---",
  'title: "VARG-Tools User Guide"',
  'author: "Bolton and Jensen"',
  "date: last-modified",
  "format:",
  "  pdf:",
  "    toc: true",
  "    toc-depth: 2",
  "    number-sections: false",
  "    colorlinks: true",
  "    documentclass: report",
  "    geometry:",
  "      - margin=1in",
  "---",
  "",
  "<!-- Generated by docs/build_in_app_guide.R from the modular chapter files. Do not edit directly. -->",
  source_digest_marker,
  "",
  paste0("**Version:** ", app_version),
  ""
)

for (i in seq_along(chapters)) {
  chapter <- chapters[[i]]
  if (i > 1L) {
    combined_qmd <- c(combined_qmd, "", paste0("# ", chapter$title), "")
  }
  combined_qmd <- c(combined_qmd, rewrite_chapter_links(chapter$body))
}

writeLines(combined_qmd, combined_qmd_file, useBytes = TRUE)
cat("Built", normalizePath(output_file, winslash = "/"), "\n")
cat("Built", normalizePath(combined_qmd_file, winslash = "/"), "\n")
