script_arg <- commandArgs(trailingOnly = FALSE)[grep("^--file=", commandArgs(trailingOnly = FALSE))]
script_path <- normalizePath(sub("^--file=", "", script_arg), winslash = "/")
app_dir <- dirname(dirname(script_path))

guide_file <- file.path(app_dir, "docs", "VARG-Tools_User_Guide.md")
combined_qmd_file <- file.path(app_dir, "docs", "guide", "VARG-Tools_User_Guide.qmd")
guide_asset_dir <- normalizePath(file.path(app_dir, "docs", "guide"), winslash = "/", mustWork = TRUE)
builder_file <- file.path(app_dir, "docs", "build_in_app_guide.R")
chapter_files <- c(
  "index.qmd",
  "getting-started.qmd",
  "walkthrough.qmd",
  "processing.qmd",
  "visualization.qmd",
  "chronology.qmd",
  "troubleshooting.qmd",
  "reference.qmd"
)
guide_asset_files <- c(
  "build_workflow_map.R",
  "workflow-map.png",
  "ilr-concept.png",
  "gmm-concept.png",
  "sc-concept.png",
  "phase-concept.png"
)
source_files <- c(
  builder_file,
  file.path(guide_asset_dir, chapter_files),
  file.path(guide_asset_dir, guide_asset_files)
)
source_digest <- paste(
  paste0(basename(source_files), "=", unname(tools::md5sum(source_files))),
  collapse = ";"
)
source_digest_marker <- paste0("<!-- Guide source digest: ", source_digest, " -->")

rewrite_guide_markdown_images <- function(markdown_text, transform_path) {
  pattern <- "!\\[([^\\]]*)\\]\\((guide-assets/[^)]+)\\)"
  matches <- gregexpr(pattern, markdown_text, perl = TRUE)
  if (matches[[1]][1] == -1) return(markdown_text)

  image_refs <- regmatches(markdown_text, matches)[[1]]
  replacements <- vapply(image_refs, function(image_ref) {
    alt_text <- sub(pattern, "\\1", image_ref, perl = TRUE)
    relative_path <- sub(pattern, "\\2", image_ref, perl = TRUE)
    sprintf("![%s](%s)", alt_text, transform_path(relative_path))
  }, character(1))
  regmatches(markdown_text, matches) <- list(replacements)
  markdown_text
}

rewrite_guide_html_images <- function(html_text, transform_path) {
  pattern <- '(<img[^>]+src=")([^"]*guide-assets/[^"]+)("[^>]*>)'
  matches <- gregexpr(pattern, html_text, perl = TRUE)
  if (matches[[1]][1] == -1) return(html_text)

  image_tags <- regmatches(html_text, matches)[[1]]
  replacements <- vapply(image_tags, function(image_tag) {
    prefix <- sub(pattern, "\\1", image_tag, perl = TRUE)
    src <- sub(pattern, "\\2", image_tag, perl = TRUE)
    suffix <- sub(pattern, "\\3", image_tag, perl = TRUE)
    paste0(prefix, transform_path(src), suffix)
  }, character(1))
  regmatches(html_text, matches) <- list(replacements)
  html_text
}

guide_image_data_uri <- function(relative_path) {
  asset_path <- file.path(guide_asset_dir, sub("^guide-assets/", "", relative_path))
  if (!file.exists(asset_path)) stop("Missing guide asset: ", relative_path, call. = FALSE)

  extension <- tolower(tools::file_ext(asset_path))
  mime_type <- switch(
    extension,
    png = "image/png",
    jpg = "image/jpeg",
    jpeg = "image/jpeg",
    svg = "image/svg+xml",
    gif = "image/gif",
    webp = "image/webp",
    "application/octet-stream"
  )
  base64enc::dataURI(file = asset_path, mime = mime_type)
}

render_guide_markdown_fragment <- function(markdown_text) {
  if (requireNamespace("commonmark", quietly = TRUE)) {
    return(commonmark::markdown_html(
      markdown_text,
      extensions = c("table", "autolink", "strikethrough")
    ))
  }

  external_prefix <- "https://guide-assets.local/"
  safe_markdown <- gsub(
    "\\((/)?guide-assets/",
    paste0("(", external_prefix),
    markdown_text,
    perl = TRUE
  )
  safe_html <- markdown::markdownToHTML(text = safe_markdown, fragment.only = TRUE, options = "")
  gsub(external_prefix, "guide-assets/", safe_html, fixed = TRUE)
}

options(warn = 2)
guide_content <- paste(readLines(guide_file, warn = FALSE, encoding = "UTF-8"), collapse = "\n")

required_text <- c(
  "Generated by docs/build_in_app_guide.R",
  "# First Successful Run",
  "# Processing Geochemistry",
  "# Comparing and Correlating Records",
  "# Generating Chronology Models",
  "# Troubleshooting",
  "# Reference",
  "The projection is a screening view",
  "exact-anchor, monotonic, piecewise-linear mapping",
  "does not run OxCal"
)
stopifnot(all(vapply(required_text, grepl, logical(1), x = guide_content, fixed = TRUE)))
stopifnot(grepl(source_digest_marker, guide_content, fixed = TRUE))
stopifnot(!grepl("\\.qmd(?:#|\\))", guide_content, perl = TRUE))
stopifnot(!grepl("0.9.7.1", guide_content, fixed = TRUE))
stopifnot(!grepl("check the R console", guide_content, ignore.case = TRUE))
stopifnot(!grepl("!\\[\\]", guide_content, perl = TRUE))

image_pattern <- "!\\[[^\\]]+\\]\\(guide-assets/([^)]+)\\)"
image_matches <- regmatches(guide_content, gregexpr(image_pattern, guide_content, perl = TRUE))[[1]]
image_names <- sub(image_pattern, "\\1", image_matches, perl = TRUE)
expected_images <- c(
  "workflow-map.png",
  "ilr-concept.png",
  "gmm-concept.png",
  "sc-concept.png",
  "phase-concept.png"
)
stopifnot(identical(sort(image_names), sort(expected_images)))
stopifnot(all(file.exists(file.path(guide_asset_dir, image_names))))

word_count <- length(strsplit(gsub("[[:space:]]+", " ", trimws(guide_content)), " ")[[1]])
heading_count <- length(grep("^#{1,3}[[:space:]]", strsplit(guide_content, "\n", fixed = TRUE)[[1]]))
stopifnot(word_count <= 6000L)
stopifnot(heading_count <= 50L)

rendered_html <- render_guide_markdown_fragment(guide_content)
stopifnot(grepl('src="guide-assets/workflow-map.png"', rendered_html, fixed = TRUE))
stopifnot(grepl('href="#first-successful-run"', rendered_html, fixed = TRUE))
stopifnot(!grepl("File 'guide-assets/", rendered_html, fixed = TRUE))

embedded_html <- rewrite_guide_html_images(rendered_html, guide_image_data_uri)
stopifnot(length(gregexpr('src="data:image/png;base64,', embedded_html, fixed = TRUE)[[1]]) == length(expected_images))
stopifnot(!grepl("guide-assets/", embedded_html, fixed = TRUE))

combined_qmd <- paste(readLines(combined_qmd_file, warn = FALSE, encoding = "UTF-8"), collapse = "\n")
stopifnot(grepl("Generated by docs/build_in_app_guide.R", combined_qmd, fixed = TRUE))
stopifnot(grepl(source_digest_marker, combined_qmd, fixed = TRUE))
stopifnot(!grepl("{{< include", combined_qmd, fixed = TRUE))
stopifnot(!grepl("\\.qmd(?:#|\\))", combined_qmd, perl = TRUE))
stopifnot(grepl("](workflow-map.png)", combined_qmd, fixed = TRUE))

cat(sprintf("guide_render_ok words=%d headings=%d images=%d\n", word_count, heading_count, length(image_names)))
